function [layout_muscle, layout_muscle_half] = get_layout_muscle

layout_muscle_half = [...
    ["Trapezius",   "Deltoid",      "Triceps"]; ...
    ["Biceps",      "ECR",          "FCR"]; ...
    ["",            "APB",          "ADM"]; ...
    ["TA",          "EDB",          "AH"]; ...
    ];

layout_muscle = ["L" + fliplr(layout_muscle_half), "R" + layout_muscle_half];
layout_muscle(layout_muscle.strlength==1) = "";
end