function [layout_scloc, cell_scloc_level, cell_scloc_lateral, ...
    layout_scloc_ext, cell_scloc_lateral_ext, ...
    vec_ix_level] = get_layout_scloc(varargin)
d.output_as_string = true;
%% Parse input
d.d_overwrite = struct;
[v, d] = inputParserCustom(d, varargin);clear d;
v = inputParserStructureOverwrite(v);
%%
layout_scloc = [...
    {'C4_L', 'C4_M', 'C4_R'}; ...
    {'C5_L', 'C5_M', 'C5_R'}; ...
    {'C6_L', 'C6_M', 'C6_R'}; ...
    {'C7_L', 'C7_M', 'C7_R'}; ...
    {'C8_L', 'C8_M', 'C8_R'}; ...
    {'T1_L', 'T1_M', 'T1_R'}; ...
    ];

cell_scloc_level = {'C4', 'C5', 'C6', 'C7', 'C8', 'T1'};
vec_ix_level = [4:9];

cell_scloc_lateral = {'L', 'M', 'R'};

layout_scloc_ext = [...
    {'C4_L', 'C4_ML', 'C4_MR', 'C4_R'}; ...
    {'C5_L', 'C5_ML', 'C5_MR', 'C5_R'}; ...
    {'C6_L', 'C6_ML', 'C6_MR', 'C6_R'}; ...
    {'C7_L', 'C7_ML', 'C7_MR', 'C7_R'}; ...
    {'C8_L', 'C8_ML', 'C8_MR', 'C8_R'}; ...
    {'T1_L', 'T1_ML', 'T1_MR', 'T1_R'}; ...
    ];
cell_scloc_lateral_ext = {'L', 'ML', 'MR', 'R'};

if v.output_as_string
    layout_scloc = string(layout_scloc);
    cell_scloc_level = string(cell_scloc_level);
    layout_scloc_ext = string(layout_scloc_ext);
    cell_scloc_lateral_ext = string(cell_scloc_lateral_ext);
    cell_scloc_lateral = string(cell_scloc_lateral);
end
end